### PR TITLE
[compiler] support windows

### LINKED ISSUE #66: [Feature Request] Support Windows develop
# 🚀 Feature Request

## Motivation

Support windows develop 

**Is your feature request related to a problem? Please describe.**

1. Move cli support compiles to the Windows binary.
2. Move compiler process Windows-style line ending (CRLF)

## Pitch

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

## Additional context

https://github.com/starcoinorg/starcoin/issues/3131

### PR DESCRIPTION
**Pull request by LemonHX**
## Motivation
close #66 

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?

yes

## Test Plan

(Share your test plan here. If you changed code, please provide us with clear instructions for verifying that your changes work.)

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/diem/diem/tree/main/developers.diem.com, and link to your PR here.)

## If targeting a release branch, please fill the below out as well

 * Justification and breaking nature (who does it affect? validators, full nodes, tooling, operators, AOS, etc.)
 * Comprehensive test results that demonstrate the fix working and not breaking existing workflows.
 * Why we must have it for V1 launch.
 * What workarounds and alternative we have if we do not push the PR.

### CODE REVIEW

**Comment by sblackshear** [comment]
Thanks for this contribution! Would you mind writing a short blurb on the `termion` -> `crossterm` switch and explaining any differences we might see in the compiler?

Code looks good to me but I'll leave the final say to @tnowacki.

**Review by tzakian — APPROVED** [review]
These changes look good to me! Thanks for the contribution. 

I agree with Sam's comment, if you could write something about this switch on the associated issue that would be great as well. I think in this case there isn't too much concern since it's tooling-only changes, but if you're eventually planning on changing things in the compiler and error reporting having a high level description of the changes would be good.

**Comment by LemonHX** [comment]
@sblackshear termion is not compatible with windows platform, and modern tui choose to use crossterm as its default backend.

**Comment by LemonHX** [comment]
@tzakian another thing is it is very difficult to run shell script in windows platform, maybe we could rewrite scripts by using python or anything crossplatform, if you are happy to see such changes i will open up a new issue.

**Comment by tzakian** [comment]
@LemonHX the github lint is still unhappy about the whitespace error since it can see it in a commit on this PR. Could you possibly squash all commits on this PR into one single commit?

As far as rewriting the shell scripts into Python, I think that's a larger question that we will need to discuss on a separate issue as it will effect CI, and I'm not sure if we'd want to make such a change at the moment. Could you possibly start an issue where we could have a discussion about this and make a decision on whether or not this is something that we would like?

**Comment by tzakian** [comment]
@LemonHX It looks like there's a merge commit left in the squash that you did. Can you squash everything down to one 
single (non-merge) commit? CI won't allow it otherwise.

**Comment by LemonHX** [comment]
@tzakian move to pr #105

**Pull request closed without merging**
