### PR TITLE
Simplify dev_setup script

### PR DESCRIPTION
**Pull request by 666lcz**
## Motivation

Per https://github.com/diem/move/issues/25, The dev_setup script installs many things (terraform, kubernetes, awscli, ...) that aren't needed to run Move. 

Aside from above-mentioned, I also looked into the following modules in dev_setup.sh and removed the Codegen tool and API build tool that are only used in `diem/diem`

<table>
<tr>
	<td> Decision
	<td> Module
	<td> Callsites in Diem/move
	<td> Callsites in Diem/Diem
<tr>
	<td> Solidity
	<td> Keep
	<td> https://github.com/diem/move/search?q=solidity
	<td> N/A
<tr>
	<td> Remove
	<td> CodeGen Tool
	<td> [N/A](https://github.com/diem/move/search?q=swift)
	<td> https://github.com/diem/diem/blob/dbbc96c7c3ae936bdf60744fd9055a5835b060d2/diem-move/transaction-builder-generator/README.md
<tr>
	<td> Remove
	<td> API Build Tool
	<td> [N/A](https://github.com/diem/move/search?q=schemathesis)
	<td> https://github.com/diem/diem/search?q=schemathesis
</table>

### Have you read the [Contributing Guidelines on pull requests]

Yes

## Test Plan

Ran docker build locally and verify that the build was successful
```
DOCKER_BUILDKIT=0 docker build -t 666lcz/move-1 .
```

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/diem/diem/tree/main/developers.diem.com, and link to your PR here.)

## If targeting a release branch, please fill the below out as well

 * Justification and breaking nature (who does it affect? validators, full nodes, tooling, operators, AOS, etc.)
 * Comprehensive test results that demonstrate the fix working and not breaking existing workflows.
 * Why we must have it for V1 launch.
 * What workarounds and alternative we have if we do not push the PR.

### CODE REVIEW

**Review by sblackshear — DISMISSED** [review]
Beautiful, thank you!!

**Comment by 666lcz** [comment]
Sorry forgot to update https://github.com/diem/move/blob/1b1dd0bc3c6780b77517bebbc71d39e7cae0be00/.github/actions/build-setup/action.yml#L60 for the second and third commit. They should be fixed now. Could you re-run the workflow?

**Review by sblackshear — DISMISSED** [review]
/land

**Pull request merged**
