### PR TITLE
upgrade clap to v3

### PR DESCRIPTION
**Pull request by LemonHX**
Signed-off-by: lemonhx <lemonhx@lemonhx.tech>

## Motivation

we need to upgrade move deps to clap v3, and #17 seems blocking for a long time

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?
yes

## Test Plan

(Share your test plan here. If you changed code, please provide us with clear instructions for verifying that your changes work.)

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/diem/diem/tree/main/developers.diem.com, and link to your PR here.)

## If targeting a release branch, please fill the below out as well

 * Justification and breaking nature (who does it affect? validators, full nodes, tooling, operators, AOS, etc.)
 * Comprehensive test results that demonstrate the fix working and not breaking existing workflows.
 * Why we must have it for V1 launch.
 * What workarounds and alternative we have if we do not push the PR.

### CODE REVIEW

**Comment by LemonHX** [comment]
@wrwg PTAL

**Review by wrwg — DISMISSED** [review]
Wow! Totally awesome, thanks for doing this!! 

@sblackshear FYI

**Comment by LemonHX** [comment]
@wrwg seems like linker OOM？

**Comment by wrwg** [comment]
/land again perhaps a flake, could be also disk out of space

**Pull request merged**
