### PR TITLE
[move-repo] PR to test bors.

### PR DESCRIPTION
**Pull request by wrwg**
This is a dummy PR to test bors which seems to be down. It removes some unneeded deps from move-to-yul.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

### CODE REVIEW

**Review by junkil-park — DISMISSED** [review]

**Comment by wrwg** [comment]
/land this to fully test the flow, and the change also some little use (minimizing deps).

**Pull request merged**
