### PR TITLE
Update Move book off of head, add unit testing section

### PR DESCRIPTION
**Pull request by tzakian**
This PR adds a section to the Move book on unit testing, and also updates the book to be built off of `diem/main` -- so picks up the new syntax changes to `assert!`

### CODE REVIEW

**Comment by bob-wilson** [comment]
We had previously tried to keep the published docs aligned with the latest release. Are you proposing to change that in general or is this a one-off change to temporarily sync up to a more recent version?

**Comment by tzakian** [comment]
Longer-term, I'd propose that that we change it in general until we have Move releases given the recent developments. Near-term I'm happy to hold-off on the larger question, and have this be a one-off change  for the hackathon since they will be building off of `main`, and it would be good for the book to have the updated syntax/docs for that along with docs on unit testing.

**Comment by bob-wilson** [comment]
OK, I'm fine with it as a one-off. In general, though, we should work toward a more consistent answer about whether people should use the main branch or the latest release.

**Review by bob-wilson — APPROVED** [review]
I skimmed through this and the changes do indeed look like they all match up with the latest content from the main branch.

**Pull request merged**
