### PR TITLE
Fix serde serialization leading to compile error

### PR DESCRIPTION
**Pull request by areshand**
## Motivation

Fix the issues described here https://github.com/diem/move/issues/126

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

cargo x lint && cargo xfmt && cargo xclippy --all-targets passed
cargo test -p move-core-types passed

### CODE REVIEW

**Review by sblackshear — DISMISSED** [review]
/land

**Comment by davidiw** [comment]
I think we need to revert this PR and return to jolestar's PR. This creates an asymmetry in serialization / deserialization which is a disaster waiting to happen.

@areshand / @sblackshear any objections?
I can't tag jolestar.

I'm happy to approve and considering it hasn't been reported and is so new, I think we should be able to safely do this.

**Pull request merged**
